Expose TEMP_FAILURE_RETRY for more systems
TEMP_FAILURE_RETRY is defined in bionic and glibc but missing in musl
and BSD libc. So, make the conditional inclusive, leaving unusual
systems to #ifndef guard.

src/gpuvis_utils.cpp:503:18: error: use of undeclared identifier 'TEMP_FAILURE_RETRY'
    int source = TEMP_FAILURE_RETRY( open( filename, O_RDONLY, 0 ) );
                 ^
src/gpuvis_utils.cpp:504:16: error: use of undeclared identifier 'TEMP_FAILURE_RETRY'
    int dest = TEMP_FAILURE_RETRY( open( newfilename, O_WRONLY | O_CREAT, 0644 ) );
               ^
src/gpuvis_utils.cpp:514:28: error: use of undeclared identifier 'TEMP_FAILURE_RETRY'
            ssize_t size = TEMP_FAILURE_RETRY( read( source, buf, BUFSIZ ) );
                           ^
src/gpuvis_utils.cpp:517:24: error: use of undeclared identifier 'TEMP_FAILURE_RETRY'
                size = TEMP_FAILURE_RETRY( write( dest, buf, size ) );
                       ^