libtraceevent: Add missing header for AF_* macros
src/libtraceevent/src/event-parse.c:5232:23: error: use of undeclared identifier 'AF_INET'
        if (sa->ss_family == AF_INET) {
                             ^
src/libtraceevent/src/event-parse.c:5245:30: error: use of undeclared identifier 'AF_INET6'
        } else if (sa->ss_family == AF_INET6) {
                                    ^