cmake: Pass -std=c++11 with Clang like GCC
GCC >= 11 and Clang >= 16 default to -std=gnu++17 but std::ptr_fun was
deprecated since C++11 and removed since C++17.

src/gpuvis_utils.cpp:310:30: error: no member named 'ptr_fun' in namespace 'std'
             std::not1( std::ptr_fun< int, int >( std::isspace ) ) ) );
                        ~~~~~^
src/gpuvis_utils.cpp:317:30: error: no member named 'ptr_fun' in namespace 'std'
             std::not1( std::ptr_fun< int, int >( std::isspace ) ) ).base(), s.end() );
                        ~~~~~^
src/gpuvis_utils.cpp:353:31: error: no member named 'ptr_fun' in namespace 'std'
                         std::ptr_fun< int, int >( &std::ispunct ) );
                         ~~~~~^